### ISSUE TITLE
Make the plugin works on geolocator 6.0.0-rc.1 to fix the permission denied in iOS and Android.

### ISSUE THREAD

**Issue by madz** [humazed/google_map_location_picker#102]
There was a bug in geolocator https://github.com/Baseflow/flutter-geolocator/issues/430 that makes the location permission being denied even if the user allows the access.

It was fixed in geolocator 6.0.0-rc.1 but the google_map_location_picker 3.3.3 depends on geolocator ^5.3.2+2

**Comment by humazed** [comment]
Thanks for the suggestion but I probably would wait until it is stable.
but if someone made a PR I would most likely merge it.

**Comment by humazed** [comment]
started working on it.
