### ISSUE TITLE
AndroidX compitiblity

### ISSUE THREAD

**Issue by M9Apar** [humazed/google_map_location_picker#11]
Hi,i must say excellent work, i tried your plugging with Flutter App, initially i am able to run app and perform desire operations,
but i tried it with androidX component, it will give me below error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.legacy:legacy-support-core-utils' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

at this point i can't bypass androidX so is there any near solutions for it?

**Comment by humazed** [comment]
I'm using this plugin in many of my apps that use AndroidX are you sure this plugin is responsible for this error.

when you remove it the error disappears and when you add it the error reappears.

**Comment by M9Apar** [comment]
yup i tried it and it will work if i remove plugging and it won't work while i add dependency

**Comment by humazed** [comment]
can you create and share a project where I can reproduce this issue
