### ISSUE TITLE
Is it possible to get the latitude/longitude of any arbitrary location on the map?

### ISSUE THREAD

**Issue by kuchienkz** [humazed/google_map_location_picker#110]
The submit button keeps hidden when there is no Place selected. I just want the latitude/longitude of any arbitrary location on the map (using the pin).

**Comment by humazed** [comment]
You should be able to select any location, what are you seeing that prevents you from doing so?

**Comment by kuchienkz** [comment]
Silly me... it was someone else's package haha. I don't know how can I reach your repo, but thanks to that I found yours. Yours works just like what I want. Thanks!
