### ISSUE TITLE
IOS Real Device Taking too much time to open the map. Please guide me.

### ISSUE THREAD

**Issue by kadnan0900** [humazed/google_map_location_picker#114]

**Comment by hennonoman** [comment]
because the desired location accuracy is high,
the package does not allow to change this to medium or low

**Comment by kadnan0900** [comment]
@hennonoman how i can solve this issue ?

**Comment by kadnan0900** [comment]
@humazed can you guide me how to solve this issue ?

**Comment by hennonoman** [comment]
I fork this library and solve the problem you can get it from my Github

**Comment by hennonoman** [comment]
`google_map_location_picker:
    git:
      url: https://github.com/hennonoman/google_map_location_picker.git`

**Comment by humazed** [comment]
added `desiredAccuracy` in 4.0.0

**Comment by kadnan0900** [comment]
@hennonoman @humazed how i can get the current location in map ? when i open the map my current location does not shown my current location ..
![IMG_87F320248BFC-1](https://user-images.githubusercontent.com/51955352/95116460-81bf8800-0760-11eb-91d3-d714e03492cb.jpeg)

**Comment by hennonoman** [comment]
I already fork the v4 of the package and tried to solve this problem.
try this version https://github.com/hennonoman/google_map_location_picker

and I made a pull request for this editng
