### ISSUE TITLE
Getting error Could not signal service com.apple.WebKit.WebContent

### ISSUE THREAD

**Issue by SalilThreeplus** [humazed/google_map_location_picker#115]
When I add the io.flutter.embedded_views_preview flag in info.plist, I get the error Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service and the application is stuck on splash screen. If I don't add this flag then maps is not loaded. Application works fine in debug mode, this is the problem when I run app in release mode or download from TestFlight.

Any help is appreciated.
Below is the Info.plist ss

<img width="1680" alt="93014843-23284380-f5d2-11ea-9485-b5b6ee43229e" src="https://user-images.githubusercontent.com/58214996/93205968-48ee4d80-f776-11ea-8f45-1d6fb0c71138.png">

**Comment by humazed** [comment]
Could you try this with google maps plugin and if you can repreduce it. It
would be better if you open an issue there I guess you would get better
assistance
And this is working for me on many apps and didn't face any problems when
uploading to the app store
