### ISSUE TITLE
No need to access GPS

### ISSUE THREAD

**Issue by djsliders** [humazed/google_map_location_picker#12]
Hi,
First thank you for the plugin.
One question: Why do you need the GPS enabled to pick a location?
I mean you don't need it unless you want to share your own position.
If my GPS is disabled, the plugin is not showing the map and I cannot pick a location, even through I want to share a position of something not related to my position at all.
Do you think you can change that? If there is already the button for "Showing my position", I think it is enough no?

Thank you

**Comment by humazed** [comment]
I use the GPS to center the map on the user current location and to show the blue dot on the google maps.

will see if it's easy to make it optional.

**Comment by djsliders** [comment]
That would be great to center If and only if the GPS is available, otherwise show a default position (no error message shown).
To see the current position, there is the button already available in Google Maps, I would think it is enough no?

Thank you for the quick reply and your work.

**Comment by humazed** [comment]
would look into it but currently, I have a very tight deadline
hopefully in 5 days will be able to make this update.
a PR is always welcomed.

**Comment by djsliders** [comment]
Do I need special permissions to do PR? I tried to push on a branch to create the PR but permissions denied.

**Comment by humazed** [comment]
you need to create a fork and edit your fork and then create the PR

**Comment by djsliders** [comment]
Thank you for the quick merge and release!
:)
