### ISSUE TITLE
Not working with stable google_maps_flutter 1.0.2

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [humazed/google_map_location_picker#121]
Hey, I am getting this error while trying to run pub get.

<img width="988" alt="Screenshot 2020-10-04 at 13 52 02" src="https://user-images.githubusercontent.com/36572426/95014752-3bc3d080-0649-11eb-8680-5a0553118d1a.png">

This is my pubscpec.yaml:

<img width="988" alt="Screenshot 2020-10-04 at 13 55 47" src="https://user-images.githubusercontent.com/36572426/95014765-50a06400-0649-11eb-9e39-74912603638f.png">

**Comment by humazed** [comment]
I will update the lib to use the latest stable asap

**Comment by humazed** [comment]
you could in the meantime use an older version of google_maps_flutter

**Comment by aleksandar-radivojevic** [comment]
Ok thanks bro

**Comment by humazed** [comment]
fixed in 4.0.0
