### ISSUE TITLE
Can't use latest build_runner package with current google_map_location_picker version

### ISSUE THREAD

**Issue by kuchienkz** [humazed/google_map_location_picker#128]
`Because build_runner >=1.10.3 depends on build_resolvers ^1.4.0 which depends on analyzer ^0.40.1, build_runner >=1.10.3 requires analyzer ^0.40.1.
And because intl_translation >=0.17.8 <=0.17.10 depends on analyzer >=0.36.0 <0.40.0, build_runner >=1.10.3 is incompatible with intl_translation >=0.17.8 <=0.17.10.
And because google_map_location_picker 4.0.0 depends on intl_translation >=0.17.9 <=0.17.10 and no versions of google_map_location_picker match >4.0.0 <5.0.0, build_runner >=1.10.3 is incompatible with google_map_location_picker ^4.0.0.
So, because MY_APP depends on both google_map_location_picker ^4.0.0 and build_runner ^1.10.4, version solving failed.
pub get failed (1; So, because MY_APP depends on both google_map_location_picker ^4.0.0 and build_runner ^1.10.4, version solving failed.)
`

The said packages:
- **google_map_location_picker ^4.0.0**
- **build_runner ^1.10.4** (latest)

Currently working version:
- **build_runner ^1.10.2**

**Comment by sarbogast** [comment]
Same problem here. Did you find a workaround?

**Comment by humazed** [comment]
it's just a dev dependency you could PayPass it until intl_translation is updated by 
```
dependency_overrides:
  analyzer: 0.41.0
```
