### ISSUE TITLE
because flutter_location_demo depends on both google_map_location_picker ^4.1.2+1 and flutter_localizations any from sdk, version solving failed.

### ISSUE THREAD

**Issue by UjjawalPanchal** [humazed/google_map_location_picker#135]
Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and google_map_location_picker >=3.3.1 depends on intl >=0.16.0 <=0.16.1, flutter_localizations from sdk is incompatible with google_map_location_picker >=3.3.1.
So, because flutter_location_demo depends on both google_map_location_picker ^4.1.2+1 and flutter_localizations any from sdk, version solving failed.
pub get failed (1; So, because flutter_location_demo depends on both google_map_location_picker ^4.1.2+1 and flutter_localizations any from sdk, version solving failed.)

I am getting this error can anyone help me with this?

**Comment by remymumoh** [comment]
me too, you've gotten a solution?

**Comment by humazed** [comment]
should be fixed in `4.1.4`
