### ISSUE TITLE
Address issue

### ISSUE THREAD

**Issue by dimpleagola** [humazed/google_map_location_picker#14]
I got lat-lng . But i didn't got address. Address is null. Every time show unnamed road.

**Comment by humazed** [comment]
Did you enable the APIs in your google cloud console as mentioned [here](https://github.com/humazed/google_map_location_picker#getting-started)

**Comment by dimpleagola** [comment]
Thanks..  Now it is working..

**Comment by HinnaRutaba** [comment]
I just created a paid account after reading all issues and replies on them and generated new API key but issue is still same. Can you send me your API Key for testing purpose?
