### ISSUE TITLE
Because no versions of google_map_location_picker match >4.1.6 <5.0.0 and demo depends on google_map_location_picker ^4.1.6, version solving failed.

### ISSUE THREAD

**Issue by davemg3** [humazed/google_map_location_picker#140]
Hello Mr,
There is again the similar bug of previous version #135

`Because google_map_location_picker 4.1.6 depends on flutter_localizations any from sdk which depends on intl 0.17.0, google_map_location_picker 4.1.6 requires intl 0.17.0.
And because google_map_location_picker 4.1.6 depends on intl >=0.15.3 <=0.17.0-nullsafety.2, google_map_location_picker 4.1.6 is forbidden.
So, because no versions of google_map_location_picker match >4.1.6 <5.0.0 and bubble_pro depends on google_map_location_picker ^4.1.6, version solving failed.`

Can you observe it too?

**Comment by davemg3** [comment]
Ok i found i... i was working on the Master  branch...working with a switch on Flutter stable branch

**Comment by saschaernst** [comment]
I guess the problem is back with Flutter 2...

**Comment by SmarterVision** [comment]
> I guess the problem is back with Flutter 2...

Yeah, also for me the same problem with Flutter 2.0.1

**Comment by humazed** [comment]
4.1.7 should fix it
