### ISSUE TITLE
Flutter 2.0.1 depends on both intl 0.17.0 and google_map_location_picker ^4.1.6.

### ISSUE THREAD

**Issue by s3bok** [humazed/google_map_location_picker#143]
I updated Flutter to 2.0.1 and get the next error:
**depends on both intl 0.17.0 and google_map_location_picker ^4.1.6.**

meanwhile I back to 1.22.6

**Comment by humazed** [comment]
working on an update will be released very soon.

**Comment by humazed** [comment]
4.1.7 should be compatible
