### ISSUE TITLE
Every place is showing only unamed place

### ISSUE THREAD

**Issue by muhammednazil** [humazed/google_map_location_picker#146]
i didn't get the correct name of the place location picker

**Comment by muhammednazil** [comment]
the location picker returns the address as null , there is correct lat and long and place id also null... could anyone can tell me what  is the problem ?

**Comment by muhammednazil** [comment]
LocationResult{address: null, latLng: LatLng(25.354604756652517, 51.18133004754782), placeId: null}

**Comment by muhammednazil** [comment]
Please help me as soon as possible

**Comment by Stevensie95** [comment]
Did you enabled billing account and bind your billing account to the service?

**Comment by ashokv1337** [comment]
I am also stuck in same problem any suggestion/solution please.

**Comment by sho-ocker** [comment]
Also having problems with this. Would appreciate help! I enabled all required APIs on google maps platform

**Comment by muhammednazil** [comment]
Thank you everyone
