### ISSUE TITLE
Unnamed place issue

### ISSUE THREAD

**Issue by iLeafSolutionsPvtLtd** [humazed/google_map_location_picker#16]
It's not fetching the location address or name. Instead, it keeps showing the unnamed location

**Comment by humazed** [comment]
and don't forget to enable in https://console.cloud.google.com/google/maps-apis/

Maps SDK for Android
Maps SDK for iOS
Places API
Geolocation API
Geocoding API

**Comment by DanielSmith1239** [comment]
I'm having the same issue, but I've enabled all of the apis.

**Comment by vivinapriyanti** [comment]
i've already enable API that's you mention above. but still unnamed place. is there any ways to show place name or street's name?

**Comment by humazed** [comment]
Did you make sure the billing is enabled for your key?

**Comment by HinnaRutaba** [comment]
I don't have the billing account and I am facing the same issue. Is it necessary to have a billing account to use this?

**Comment by humazed** [comment]
Yes, it's a google maps limitation, not something specifically with this library.

**Comment by HinnaRutaba** [comment]
I just created a paid account after reading all issues and replies on them and generated new API key but issue is still same. Can you send me your API Key for testing purpose?

**Comment by Saddi993** [comment]
location is working fine in debug app but not working on build app. any one facing this type of issue?

**Comment by hetsgandhi** [comment]
Even after creating a billing account, i am getting the issue of Unnamed place. Please Help.

**Comment by lzzy12** [comment]
Getting this even after enabling the APIs

**Comment by pedrobrochero** [comment]
What about a simple flag when app doesn't not require place, just the location? Something like:
bool placesSearchEnabled = true
and when false just hide the search bar and the result card, just show a fab for submit. 

By the way, right now google_map widget is showing zoom buttons in the bottomRight corner and the result card overlaps it.

**Comment by darmie** [comment]
This issue persists on lates version of this plugin, and yes billing is enabled.
