### ISSUE TITLE
IOS Freezing issue

### ISSUE THREAD

**Issue by Adevien** [humazed/google_map_location_picker#17]
Hi, the iOS part in the example / custom project when you call the request the map won't load only the load circle going forever and when you press the searchbar the application will freeze.

**Comment by humazed** [comment]
does this happen with the sample project?

**Comment by Adevien** [comment]
Yes

**Comment by humazed** [comment]
I have updated the example app
please update it and try again and don't forget to add your key [here](https://github.com/humazed/google_map_location_picker#ios)
and please take a look at the [video](https://www.youtube.com/watch?v=Ev1tqijch1o) I uploaded for the ios and enable the location in the simulator.

**Comment by Adevien** [comment]
I managed to fix just now, there was an issue with Cache / Iphone 11 Max Pro IOS 13.4 , i tried a new emulator for that version and it worked.

**Comment by humazed** [comment]
great to hear that.
