### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by CarolineJeni** [humazed/google_map_location_picker#18]
Target of URI doesn't exist: 'package:google_map_location_picker_example/keys.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

Undefined name 'apiKey'.
Try correcting the name to one that is defined, or defining the name.

**Comment by xni06** [comment]
@CarolineJeni create a new file called `libs/keys.dart` and add the following line and substituting _blah_ with your API key...

```
var apiKey = 'blah';
```

**Comment by humazed** [comment]
I think @xni06 answer solves this issue feel free to reopen if it doesn't.

**Comment by eslamwael74** [comment]
Same error @humazed

**Comment by eslamwael74** [comment]
Please, help me!
my issue not the same #25
