### ISSUE TITLE
Include my license

### ISSUE THREAD

**Issue by blackmann** [humazed/google_map_location_picker#2]
I am the original author of majority of the code (verbatim) in this repository. You will need to include my license and subsequent license as credit.

Here ->> https://github.com/blackmann/locationpicker.git

However, it will be appropriate to contribute to my library if yours has any more value than what mine provides. This reduces clutter of libraries that perform the same function in the Flutter ecosystem.

Thanks.

**Comment by jogboms** [comment]
Was about to create this same issue the very moment I saw this library. Collaboration is KEY!

**Comment by humazed** [comment]
I have taken the search bar from your library, thanks for it.
but I have different design specifications for my app and when I started working on it there was not location picker plugin available so I had to make this one. 
thank for your plugin it's a great one. will add credit to you.

**Comment by blackmann** [comment]
Apparently you forked my code. So what do you mean by "there was not location picker available...".


For instance: https://github.com/blackmann/locationpicker/blob/58bb3f5e2bfb331f5aa1d3610820c8dd021753ae/lib/place_picker.dart#L43

You just refactored it into another file 
![here](https://user-images.githubusercontent.com/5024388/64021707-76953400-cb2c-11e9-98e0-3d67a25b9c0e.PNG)

**Comment by humazed** [comment]
I mean when I started working on it, there was no plugin available.
that's part of the search bar.

**Comment by humazed** [comment]
when I finished it I saw you have just published your plugin and I liked the auto-complete so I added it to mine.

**Comment by jogboms** [comment]
Wow!

**Comment by humazed** [comment]
@jogboms I don't know if this is the good or bad kind of wow
