### ISSUE TITLE
Failed when i added latest version of intl

### ISSUE THREAD

**Issue by programmermager** [humazed/google_map_location_picker#20]
please update dependency of intl into latest version. i got error when i add google_map_location_picker and intl together. it says

> Because every version of google_map_location_picker depends on flutter_localizations any from sdk which depends on intl 0.15.8, every version of google_map_location_picker requires intl 0.15.8.
So, because e_power_app depends on both google_map_location_picker ^2.1.1 and intl ^0.16.0, version solving failed.

**Comment by humazed** [comment]
The current version of intl is 

https://github.com/humazed/google_map_location_picker/blob/8dbe7c065c2e31680b00fb7340197d16a8d23e8f/pubspec.yaml#L17

so it should be compatible with `intl ^0.16.0`
which version of Flutter are you using?
