### ISSUE TITLE
IOS: Map not loading

### ISSUE THREAD

**Issue by arunsomant** [humazed/google_map_location_picker#22]
the map won't load only the load circle going forever, only in real devices with ios 13 and 12. it is working fine in simulator and ios 10(iPhone 5) real devices.

**Comment by humazed** [comment]
Thanks for the report will try to run it ios 12 iPhone 5s and see what's
the problem.

**Comment by humazed** [comment]
I have tried it on a real device iPhone 5s and it works fine, do you see any error in the console?
