### ISSUE TITLE
`google map location picker` does not specify a Swift version

### ISSUE THREAD

**Issue by iAbdalllah** [humazed/google_map_location_picker#23]
hello

i got this error when i'm trying to run the app 

- `google_map_location_picker` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by humazed** [comment]
does this happen with the sample project because I can't reproduce your problem.

**Comment by humazed** [comment]
Update to `google_map_location_picker: ^2.1.2`

you also need to edit your `Podfile`
```
target 'Runner' do
  use_frameworks! # <--- add this
  ...
end
```

See this [issue](https://github.com/flutter/flutter/issues/16049) for more details.
