### ISSUE TITLE
Optionally disable automatic address lookup

### ISSUE THREAD

**Issue by alfredjingle** [humazed/google_map_location_picker#28]
Hi!

Firstly, just wanted to say this package is really awesome. Thanks for making it!

I was just wondering whether it would be possible to optionally switch off the automatic reverse geocoding each time the map is moved? Google Maps Geocoding API costs 5.00 USD per 1000 requests, so the costs could increase quite rapidly even with a small to medium-sized user base, since it's easy to fire off a large number of requests just by moving the map around.

I'll fork the repo for now so I can chuck something together for the project I'm working on. If you think this is a worthwhile feature, am happy to lend a hand with it.

Thanks!

**Comment by humazed** [comment]
This will increase the complexity of the codebase for a feature that I think not many would use as google offers a 200$ a month free credit which is very generous and should cover most small to medium-sized projects.

if you could share the link of your fork after you finish so if anyone has the same requirements use it.

**Comment by alfredjingle** [comment]
Here's the fork which implements this: https://github.com/alfredjingle/google_map_location_picker/tree/disable-address-lookup
