### ISSUE TITLE
Screen overlay detected blocks Android permissions

### ISSUE THREAD

**Issue by iLeafSolutionsPvtLtd** [humazed/google_map_location_picker#29]
This issue was detected in the latest version of the plugin and it can be recreated in a fresh install of the app in Marshmallow devices. This cause the user to not enable the location permission and results in an overlay permission dialog

**Comment by humazed** [comment]
Can you share a video of the problem? I have tried it on Marshmallow and everything is working fine.
and please make sure it happens on the sample application.

**Comment by humazed** [comment]
It's not a problem with the library it's a security version in android and happens in all applications.
