### ISSUE TITLE
How to restrict my api key

### ISSUE THREAD

**Issue by janosroden** [humazed/google_map_location_picker#31]
Hi,
We used your great package and as our app getting ready to production we started to review it from security point of view.
Do you have any advice how can I restrict my api key? The standard app restriction would be the best but it doesn't work due to the simple api call.
The problematic line is https://github.com/humazed/google_map_location_picker/blob/master/lib/src/map.dart#L242

Any help would be appreciated

**Comment by janosroden** [comment]
I found this info
https://groups.google.com/d/msg/google-cloud-endpoints/I-u3sAUU3Ts/AjdAsWkjAwAJ
and this
https://github.com/cloudendpoints/endpoints-management-python/blob/master/endpoints_management/control/wsgi.py#L476

I succeeded with the ios but not with android

**Comment by humazed** [comment]
What did you do to make it work for ios?

and I think restricting it would be a not trivial work, as this call requires a web apiKey.

see this for a possible solution.
https://github.com/lejard-h/google_maps_webservice/issues/56

I would look into it myself later this week. if you could update this issue with your progress it would be very helpful.

**Comment by janosroden** [comment]
Restricting the api key requires some setup in google cloud console. You can say 'This api key can be used only with XY bundle id'. And the request should contain the bundle id. This is not a 100% solution, but better than nothing and this is the maximum protection which offered by google.

You just have to add extra headers to the GET request, for example this call worked:

curl -v -H 'X-Ios-Bundle-Identifier: BUNDLE_ID' 'https://maps.googleapis.com/maps/api/geocode/json?latlng=47.50774074747785,19.055784791707993&key=API_KEY'

I tried with the android headers too but unfortunately they didn't work

**Comment by janosroden** [comment]
Ah, I just win with android:

curl -v -H 'X-Android-Package: PACKAGE_NAME' -H 'X-Android-Cert: PACKAGE_SHA1_WITHOUT_COLONS' 'https://maps.googleapis.com/maps/api/geocode/json?latlng=47.50774074747785,19.055784791707993&key=API_KEY'

**Comment by janosroden** [comment]
This is the best way what I found to get the android signing cert's sha1
https://stackoverflow.com/a/54791043/1396416

The bundle id is in [package_info](https://pub.dev/packages/package_info)

**Comment by humazed** [comment]
This is not fully fixed, the PR only fixes it on the android side. 
will leave it open in the meantime.

**Comment by janosroden** [comment]
It works on ios too, I send the bundle id in headers. Android simply requires more work due to cert sha.
