### ISSUE TITLE
pickLocation() is not defined

### ISSUE THREAD

**Issue by Ziyad33** [humazed/google_map_location_picker#32]
When I try the following code:
`LocationResult result = await LocationPicker.pickLocation(context, "My_API_Key");`

it shows me an error saying the following:

> the method 'pickLocation' isn't defined for the class 'LocationPicker'

has the function name been changed? or am I doing something wrong here?

**Comment by humazed** [comment]
It's a peaking change in 3.0.0
It's replaced by the top level function showLocationPicker()

**Comment by humazed** [comment]
It's a peaking change in `v3.0.0`
It's replaced by the top-level function `showLocationPicker()`

**Comment by Ziyad33** [comment]
thanks :)
