### ISSUE TITLE
pickLocation is not a function of LocationPicker in version 3.0.0

### ISSUE THREAD

**Issue by iansamz** [humazed/google_map_location_picker#33]
noticed when I updated to version version v 3.0.0 can you please update docs as I am constrained to use provider ^3.2.0.
Thanks so much for the plugin

**Comment by humazed** [comment]
You are right I should have included it in the changelog but unfortunately, pub.dev won't allow me to just update the changelog without releasing a new version.

the 3.0.0 doesn't include any bug fixes just an api breaking change and more UI options and better defaults so no need to update until you can update provider.

**Comment by iansamz** [comment]
> You are right I should have included it in the changelog but unfortunately, pub.dev won't allow me to just update the changelog without releasing a new version.
> 
> the 3.0.0 doesn't include any bug fixes just an api breaking change and more UI options and better defaults so no need to update until you can update provider.

Thanks how I make the pickLocation call?... Is there an example you can add?

**Comment by humazed** [comment]
The readme is outdated. but the example is up to date. 
https://github.com/humazed/google_map_location_picker/blob/master/example/lib/main.dart
