### ISSUE TITLE
"Unnamed Place" issue

### ISSUE THREAD

**Issue by DanielSmith1239** [humazed/google_map_location_picker#35]
I'm getting the "unnamed place" issue, but only on android. I set my api key in the manifest per the guide, **and it's working fine on iOS**. It is not showing any map, and it is showing "Unnamed Place" in the address section on the bottom. I have all 5 of the needed APIs enabled on the Google API console. Also, no map is showing either. [Here is what the screen looks like.](https://ibb.co/C2JX8sv)

**Comment by humazed** [comment]
duplicate https://github.com/humazed/google_map_location_picker/issues/16
comment there as it's a common issue to make it as reference for future users and make sure you are using the last version.

**Comment by DanielSmith1239** [comment]
It is not the same issue. It is working perfectly for iOS.

**Comment by humazed** [comment]
There should be an error in the logs could you add it

**Comment by DanielSmith1239** [comment]
Here is how I'm showing the picker: [link](https://ibb.co/44RtTmv). Here is what the android screen shows: [https://ibb.co/x216Th5](url). The iOS screen works fine. All that prints to the debug console when the code in the first image is executed is:

    I/flutter ( 8343): RangeError (index): Invalid value: Valid value range is empty: 0
    I/flutter ( 8343): package:google_map_location_picker/src/map.dart 89:7 | position = Lat: 37.4219983, Long: -122.084

**Comment by humazed** [comment]
Most probably it's an api key problem. 
make sure of the following:
* you enabled payment for this project.
* Set the Application restrictions to none.

**Comment by DanielSmith1239** [comment]
I already confirmed both of those. I don't think it's an API key issue because I'm using the same API key for the iOS app and it works fine there.

**Comment by DanielSmith1239** [comment]
Fixed the issue: just needed to update my Android simulator.

**Comment by humazed** [comment]
Glad you fixed it I know how frustrating these issues can be.

**Comment by PrakashNaidu2662** [comment]
> Here is how I'm showing the picker: [link](https://ibb.co/44RtTmv). Here is what the android screen shows: [link](https://ibb.co/x216Th5). The iOS screen works fine. All that prints to the debug console when the code in the first image is executed is:
> 
> ```
> I/flutter ( 8343): RangeError (index): Invalid value: Valid value range is empty: 0
> I/flutter ( 8343): package:google_map_location_picker/src/map.dart 89:7 | position = Lat: 37.4219983, Long: -122.084
> ```

Facing the same issue, Could you please help me out.

**Comment by humazed** [comment]
It's a silly question but just to make sure you are replacing "KEY" with your google maps key?

**Comment by PrakashNaidu2662** [comment]
> It's a silly question but just to make sure you are replacing "KEY" with your google maps key?

I have done the same, I am getting the map view. But I am not getting the address. 

Here I am attaching the image you can see:


![Screenshot_1580807826](https://user-images.githubusercontent.com/46068233/73730748-5877d380-475d-11ea-9062-4d9724b4229a.png)

**Comment by PrakashNaidu2662** [comment]
I think it is same as #21

**Comment by humazed** [comment]
Yes, it's the same problem,  did you make sure the billing is enabled in your key?

**Comment by PrakashNaidu2662** [comment]
> Yes, it's the same problem, did you make sure the billing is enabled in your key?

I have not done the billing. Is that create this issue?

**Comment by humazed** [comment]
You should enable the billing.
