### ISSUE TITLE
error when instaling 

### ISSUE THREAD

**Issue by heshesh2010** [humazed/google_map_location_picker#38]
log error :

Running "flutter pub get" in order_vendorApp...                 
Because restaurant_rlutter_ui depends on flutter_localizations any from sdk which depends on intl 0.15.8, intl 0.15.8 is required.

So, because restaurant_rlutter_ui depends on intl ^0.16.0, version solving failed.
pub get failed (1)
Process finished with exit code 1

my code:

version: 1.2.0

environment:
  sdk: ">=2.1.0 <3.0.0"
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  mvc_pattern: ^3.4.1
  global_configuration: ^1.3.0
  http: ^0.12.0+2
  intl: ^0.16.0
  html: ^0.14.0+2
  shared_preferences: ^0.5.3+4
  flutter_html: ^0.10.4
  flutter_svg: ^0.14.2
  location: ^2.3.5
  dynamic_theme: ^1.0.0
  flutter_inappbrowser: ^1.2.2
  url_launcher: ^4.2.0+3
  firebase_messaging: ^6.0.1
  firebase_analytics: ^4.0.2
  flare_flutter: ^1.8.1
  liquid_swipe: '1.2.0'
  google_map_location_picker: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

**Comment by humazed** [comment]
You need to update flutter to the latest stable version `1.12`

**Comment by baguskto** [comment]
> You need to update flutter to the latest stable version `1.12`

it`s work for me. thanks
