### ISSUE TITLE
Need to customise language

### ISSUE THREAD

**Issue by RakhimyanTim** [humazed/google_map_location_picker#4]
Hi! Thank your for your time!
I need to customise language (ex. Ru). Please add it. Thanks!

**Comment by humazed** [comment]
I don't speak Russian so I won't be able to add it.
in 2.0.0 it's now localization ready
you can add ru version of this [file](https://github.com/humazed/google_map_location_picker/blob/master/res/values/strings_en.arb) and make a pull request or send it here and I will add it
