### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by vivekkujur** [humazed/google_map_location_picker#40]
trying to run on IOS but app is stuck on loader and getting error:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull doubleValue]: unrecognized selector sent to instance 0x1f6d87c00'
*** First throw call stack:
(0x1bafc8a48 0x1baceffa4 0x1baecc5a8 0x1bafccaf4 0x1bafcea7c 0x108a04590 0x108a04468 0x108a05550 0x1068b442c 0x10684fdbc 0x1068a6654 0x10685d9e8 0x10686209c 0x1baf4703c 0x1baf46d78 0x1baf46448 0x1baf41584 0x1baf40adc 0x1c4ec6328 0x1bf03bae0 0x104fec624 0x1badca360)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by humazed** [comment]
This stack trace is not related to the library.
This issue might happen because of the api key not valid for ios.
