### ISSUE TITLE
Loding issue with IOS

### ISSUE THREAD

**Issue by avaan** [humazed/google_map_location_picker#41]
Hi,

I am using version ^3.1.0. Its working fine in Android.
But giving issue with IOS. It stuck in loading.
The loading progress is never ending and nothing happens.

Please let me know what could be the issue.

Thanks,
Shanvaz.M

**Comment by humazed** [comment]
Did you follow the steps in https://github.com/humazed/google_map_location_picker#ios
and This issue might happen if the api key not valid for ios.

**Comment by HariprasadTechMust** [comment]
Hey, this package is working fine with android but when it comes to ios I'm stuck at the infinite loading screen and nothing happens thereafter.
Please let me know how to fix it.

Thanks,
Hari prasad

**Comment by eslamwael74** [comment]
@humazed  _initCurrentLocation#e = PlatformException(ERROR_ALREADY_REQUESTING_PERMISSION, A request for permissions is already running, please wait for it to finish before doing another request., null)

**Comment by humazed** [comment]
What device are you using and please share the output of `flutter doctor -v`

**Comment by eslamwael74** [comment]
@humazed iPhone 8
`[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.9.1+hotfix.5 at /Users/bahielfeky/Developer/flutter
    • Framework revision 1aedbb1835 (4 months ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bahielfeky/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Users/bahielfeky/Downloads/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4
[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1`

**Comment by humazed** [comment]
fixed in #42

**Comment by magic-coding** [comment]
Hello,
I'm facing the same issue after I upload my app to TestFlight. It's working on ios simulator and my device in debugging mode.
All require Apis enabled and linked with a billing account.
Also, I notice that the app keeps sending too many requests to Geocoding API while it's keep loading. 

![IMG_0580](https://user-images.githubusercontent.com/15148391/88310640-f4ec5d00-cd20-11ea-9b56-bfbe9be8b4a3.PNG)
