### ISSUE TITLE
Loading Progress never ending

### ISSUE THREAD

**Issue by eslamwael74** [humazed/google_map_location_picker#42]
The loading progress is never ending and nothing happens, throwing this error.

 _initCurrentLocation#e = PlatformException(ERROR_ALREADY_REQUESTING_PERMISSION, A request for permissions is already running, please wait for it to finish before doing another request., null)

**Comment by humazed** [comment]
It's not a problem with the library
you need to enable location in the ios simulator.

![image](https://user-images.githubusercontent.com/8838182/73811534-60c62200-47e2-11ea-98aa-a4926c7092ba.png)
