### ISSUE TITLE
google_maps_place_picker is forbidden? how to fix this issue without updating http version

### ISSUE THREAD

**Issue by jerald-jacob** [humazed/google_map_location_picker#51]
Because every version of google_maps_place_picker depends on http ^0.12.0+4 and c2c_app depends on http 0.12.0+2, google_maps_place_picker is forbidden.
So, because c2c_app depends on google_maps_place_picker any, version solving failed.
pub get failed (1; So, because c2c_app depends on google_maps_place_picker any, version solving failed.)

**Comment by humazed** [comment]
take a look at
https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution

you could use 
```
dependency_overrides:
  url_launcher: '0.12.0+4'
```
