### ISSUE TITLE
google_map_location_picker_android.iml does not exist Please correct the file content

### ISSUE THREAD

**Issue by ameeee** [humazed/google_map_location_picker#53]
Cannot load settings from file 'C:\Users\Lenovo\Pictures\LocationPickerGoogle\google_map_location_picker\android\google_map_location_picker_android.iml': File C:\Users\Lenovo\Pictures\LocationPickerGoogle\google_map_location_picker\android\google_map_location_picker_android.iml does not exist Please correct the file content

This is whtat i get when i clone this project.. any help??

**Comment by humazed** [comment]
see if one of these solutions work for you
https://stackoverflow.com/questions/35103360/iml-file-does-not-exist-android-studio

https://github.com/JetBrains/teamcity-investigations-auto-assigner/issues/14
