### ISSUE TITLE
google_api_availability is not found ?

### ISSUE THREAD

**Issue by aTeamSolace** [humazed/google_map_location_picker#60]
@humazed  The plugin `google_api_availability` doesn't have a main class defined in E:\flutter_installation\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.4\android\src\main\java\com\baseflow\googleapiavailability\GoogleApiAvailabilityPlugin.java or E:\flutter_installation\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.4\android\src\main\kotlin\com\baseflow\googleapiavailability\GoogleApiAvailabilityPlugin.kt. This is likely to due to an incorrect `androidPackage: com.baseflow.googleapiavailability` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

**Comment by humazed** [comment]
fixed in `3.3.0`
