### ISSUE TITLE
Update version for intl 0.16.1

### ISSUE THREAD

**Issue by sleith** [humazed/google_map_location_picker#62]
Hi,
Thanks for the great lib.
Would it possible to update the intl dependency to 0.16.1? because 0.16.0 is old and cause version solving failed with other libs.

Thanks :)

**Comment by humazed** [comment]
updated in 3.3.1

**Comment by sleith** [comment]
Hi,
i'm sorry but i tried 3.3.1 is still using  int 0.16.0.
Could you pls help check? thanks :)

**Comment by humazed** [comment]
what library is conflicting with this lib?
I have updated it in this line. 
https://github.com/humazed/google_map_location_picker/blob/1f507d9ffe354cc7bf39b29dc2b08ab603b57075/pubspec.yaml#L16

if you could share a minimum project that reproduced this issue that would be great.

**Comment by sleith** [comment]
Hi,
I found out it was flutter_localizations issue.
I've upgraded flutter then it works now.
Thanks a lot for your help :)
