### ISSUE TITLE
Pub get failed (1) intl version error

### ISSUE THREAD

**Issue by furkankurt** [humazed/google_map_location_picker#7]
Because every version of google_map_location_picker depends on flutter_localizations any from sdk which depends on intl 0.16.0, every version of google_map_location_picker requires intl 0.16.0.
So, because project depends on google_map_location_picker ^2.0.0+0 which depends on intl ^0.15.8, version solving failed.
pub get failed (1)

**Comment by humazed** [comment]
this is because flutter_localizations still depends on `intl: 0.15.8` waiting for the flutter team to update it.
in the meantime you can use 
` intl: '>=0.15.8 <0.16.0'`

**Comment by furkankurt** [comment]
I changed like `intl: '>=0.15.8 <0.16.0'` and solved. I also added Turkish language files and PR.

**Comment by humazed** [comment]
thanks for the PR.
