### ISSUE TITLE
Limit Location Search to a Country , Region....

### ISSUE THREAD

**Issue by GabDorilag** [humazed/google_map_location_picker#74]
Hi Ibrahim,

Not sure if this already exist, is there a way to limit Location auto complete search to certain country?
maybe additional iption to showLocationPicker. Thanks!

-- Gab

**Comment by oha2004** [comment]
I would love to see this . Any news on this ?

**Comment by GabDorilag** [comment]
no Idea yet.... personally i like this package than other location picker out there... 
but for now have to use the other one with Country limit option....

**Comment by lzzy12** [comment]
> no Idea yet.... personally i like this package than other location picker out there...
> but for now have to use the other one with Country limit option....

can you link me the plugin that supports this feature?

**Comment by lzzy12** [comment]
Great work. Thanks @Zamorite

**Comment by Zamorite** [comment]
My pleasure, @lzzy12  🙇🏽
