### ISSUE TITLE
this doesn't seem to be related to this plugin.

### ISSUE THREAD

**Issue by Shubham-Narkhede** [humazed/google_map_location_picker#75]
this doesn't seem to be related to this plugin.

_Originally posted by @humazed in https://github.com/humazed/google_map_location_picker/issues/68#issuecomment-636348833_

i also occure this issue with this plugin

**Comment by humazed** [comment]
Duplicate of #68 
Please comment on the original issue.
and could you provide a minimum reproducible project with this issue?
