### ISSUE TITLE
Translation documentation?

### ISSUE THREAD

**Issue by astrO1** [humazed/google_map_location_picker#78]
I tried everything for making a translation on your plugin, by the way, it is very good. Can you provide some sort of documentation?

**Comment by humazed** [comment]
I'm using https://github.com/long1eu/flutter_i18n
I will be migrating from it soon.
so you could use it and make a PR so I could merge it.
If you for some reason can't do it provide me with the translation file and I will do it.

**Comment by astrO1** [comment]
HI @humazed is just want to translate two words:

"Search Place"

"Find Place"

**Comment by humazed** [comment]
Could you translate the strings_en and attach it here and I will release a
new update with it.

**Comment by astrO1** [comment]
I don't see this strings_en

but this : messages_en.dart

**Comment by astrO1** [comment]
Hi @humazed I want to translate what I can do to change these two English words?
