### ISSUE TITLE
Add ability to set initial zoom

### ISSUE THREAD

**Issue by alfredjingle** [humazed/google_map_location_picker#80]
Have found that when GPS is not available so the map cannot animate to the current position, the initial zoom is a bit too high for the user to know where the map is in the country.

Have made the zoom configurable (while keeping the default value of 16) in [this commit](https://github.com/alfredjingle/google_map_location_picker/tree/set-initial-zoom). Can open a PR if you think this would be of use.

**Comment by humazed** [comment]
Yes a PR would be welcome
