### ISSUE TITLE
unnamed place issue

### ISSUE THREAD

**Issue by kittugithubpandey** [humazed/google_map_location_picker#91]
unnamed place and if i am searching any place it is giving no result

**Comment by humazed** [comment]
duplicate of #16

**Comment by shahzaib44** [comment]
You should place your api metadeta info in

<application>
   <meta-data android:name="com.google.android.geo.API_KEY" android:value="<put your api KEY here"/>  
<application>

and not in other position like for example under:

<application>
   <activity>
      <meta-data android:name="com.google.android.geo.API_KEY" android:value="<put your api KEY here"/>
   <activity>
<application>

This worked for me

**Comment by shahzaib44** [comment]
You should place metadata info in android manifest file like this:

application
   meta-data android:name="com.google.android.geo.API_KEY" android:value="<put your api KEY here"/>  
application

and not in other position like for example under:

application
   activity
      meta-data android:name="com.google.android.geo.API_KEY" android:value="<put your api KEY here"/>
   activity
application

This worked for me
