### ISSUE TITLE
In iOS map not loading.

### ISSUE THREAD

**Issue by MuthuSubramaniam** [humazed/google_map_location_picker#92]
In android this is awesome and simple. But its not working in iOS real device too.. 

![image](https://user-images.githubusercontent.com/39517706/88451860-c5f2fa00-ce8c-11ea-91ea-78775448ec9f.png)

This is the screen i am seeing in android 
![image](https://user-images.githubusercontent.com/39517706/88452114-9e049600-ce8e-11ea-972a-2b8942e1ab4d.png)

Here is my google console

![image](https://user-images.githubusercontent.com/39517706/88452142-cc827100-ce8e-11ea-8e63-79175c26f43a.png)

**Comment by truongluan280293** [comment]
May be you miss API Key for iOS in AppDelegate:

`GMSServices.provideAPIKey("API KEY")`

**Comment by humazed** [comment]
I'm closing this issue because it is inactive feel free to reopen it.
