### ISSUE TITLE
Map on Tablet not loading

### ISSUE THREAD

**Issue by dupiesdupreez** [humazed/google_map_location_picker#96]
Any emulators bigger than a certain size (not exactly sure what the maximum size is) will stop working / displaying.

Table : 
![Screenshot_1596646732](https://user-images.githubusercontent.com/6910085/89442120-8ced3c00-d74e-11ea-8aed-c6e9514c1a3e.png)

Smaller phones
![Screenshot_1596647025](https://user-images.githubusercontent.com/6910085/89442124-8f4f9600-d74e-11ea-9632-9d9803b25523.png)

**Comment by humazed** [comment]
Why did you close it what was the error?

**Comment by dupiesdupreez** [comment]
Think it was just an emulator problem. Got it working
